name: Comment when opened
on:
  issues:
    types:
      - opened
jobs:
  comment:
    permissions: write-all
    environment: Production
    runs-on: ubuntu-latest
    steps:
      - run: gh project item-add 2 --owner @me --url $ISSUE
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          ISSUE: ${{ github.event.issue.html_url }}
